export default {
  id: 1,
  first_name: 'Taylor',
  last_name: 'Swift',
  email: 'taylor@swift.com',
  phone_primary: '+1 (555) 555-9999',
  profile: {
    gender: '',
    gender_other: '',
    pronoun: '',
    pronoun_other: '',
    years_exp: '',
    job_search_status: '',
    current_job_status: '',
    current_edu_status: '',
    previous_bcorps_program: '',
    address_primary: {
      street1: '',
      street2: '',
      city: '',
      state: '',
      zip_code: '',
      country: '',
    },
    race: {
      american_indian: false,
      asian: false,
      black: false,
      hispanic: false,
      hawaiian: false,
      south_asian: false,
      white: false,
      not_listed: false,
      race_other: '',
    },
    roles: {
      advocacy_public_policy: false,
      community_engagement_outreach: false,
      data_analysis: false,
      fundraising_development: false,
      marketing_public_relations: false,
      operations_administration: false,
      program_management: false,
    },
    value_question1: '',
    value_question2: '',
  },
};
